-- SCP Armory — traductions (français par défaut, allemand, polonais)
-- Les clés sont les chaînes françaises d'origine : toute clé manquante
-- retombe sur le français. Langue choisie dans le panneau de configuration
-- (Config.Language = "fr" / "de" / "pl"), diffusée à tous les joueurs.

SCPArmory = SCPArmory or {}

SCPArmory.Translations = {
	de = {
		["ARME PRINCIPALE"] = "PRIMÄRWAFFE",
		["ARME SECONDAIRE"] = "SEKUNDÄRWAFFE",
		["TACTIQUE I"] = "TAKTISCH I",
		["TACTIQUE II"] = "TAKTISCH II",
		["GRENADE"] = "GRANATE",
		["GILET BALISTIQUE"] = "SCHUTZWESTE",
		["CASQUE"] = "HELM",
		["ARMEMENT"] = "BEWAFFNUNG",
		["PROTECTION"] = "SCHUTZ",
		["APPARENCE"] = "AUSSEHEN",
		["PRÉPARATION AU DÉPLOIEMENT"] = "EINSATZVORBEREITUNG",
		["MODIFIER L'ARME"] = "WAFFE ANPASSEN",
		["CHOIX D'ACCESSOIRE"] = "AUFSATZ WÄHLEN",
		["SÉLECTION D'ÉQUIPEMENT"] = "AUSRÜSTUNG WÄHLEN",
		["APPARENCE DE L'OPÉRATEUR"] = "AUSSEHEN DES OPERATORS",
		["— AUCUN —"] = "— KEINE —",
		["— AUCUNE —"] = "— KEINE —",
		["CHANGER D'ARME"] = "WAFFE WECHSELN",
		["—  VIDE  —"] = "—  LEER  —",
		["RETIRER TOUS LES ACCESSOIRES"] = "ALLE AUFSÄTZE ENTFERNEN",
		["SÉLECTIONNEZ D'ABORD UNE ARME"] = "WÄHLEN SIE ZUERST EINE WAFFE",
		["ARME NON ARC9 — AUCUN ACCESSOIRE DISPONIBLE"] = "KEINE ARC9-WAFFE — KEINE AUFSÄTZE VERFÜGBAR",
		["CETTE ARME N'A AUCUN EMPLACEMENT D'ACCESSOIRE"] = "DIESE WAFFE HAT KEINE AUFSATZPLÄTZE",
		["AUCUN EMPLACEMENT D'ACCESSOIRE"] = "KEINE AUFSATZPLÄTZE",
		["—  AUCUN  —"] = "—  KEINE  —",
		["CONFIGURATION"] = "KONFIGURATION",
		["AUCUN ACCESSOIRE ARC9 COMPATIBLE INSTALLÉ"] = "KEIN KOMPATIBLER ARC9-AUFSATZ INSTALLIERT",
		["ACCESSOIRES"] = "AUFSÄTZE",
		["AUCUNE ARME SÉLECTIONNÉE"] = "KEINE WAFFE AUSGEWÄHLT",
		["ARME NON ARC9 — PAS DE RAIL"] = "KEINE ARC9-WAFFE — KEINE SCHIENE",
		["PRINCIPALE"] = "PRIMÄR",
		["SECONDAIRE"] = "SEKUNDÄR",
		["‹  RETOUR"] = "‹  ZURÜCK",
		["RETOUR"] = "ZURÜCK",
		["DÉPLOYER"] = "EINSETZEN",
		["CHARGEMENT"] = "BELADUNG",
		["POIDS"] = "GEWICHT",
		["MOBILITÉ"] = "MOBILITÄT",
		["ARMURE"] = "PANZERUNG",
		["LÉGER"] = "LEICHT",
		["INTERMÉDIAIRE"] = "MITTEL",
		["LOURD"] = "SCHWER",
		["DÉGÂTS"] = "SCHADEN",
		["CADENCE"] = "FEUERRATE",
		["CONTRÔLE"] = "KONTROLLE",
		["PRÉCISION"] = "PRÄZISION",
		["VARIANTE"] = "VARIANTE",
		["ÉQUIPÉE"] = "AUSGERÜSTET",
		["GLISSER : PIVOTER   ·   MOLETTE : ZOOM   ·   CLIC MOLETTE : DÉPLACER"]
			= "ZIEHEN: DREHEN   ·   MAUSRAD: ZOOM   ·   MITTLERE TASTE: BEWEGEN",
		["BODYGROUPS AUTORISÉS PAR LE SITE"] = "VOM STANDORT ERLAUBTE BODYGROUPS",
		["Aucun bodygroup autorisé sur votre modèle."] = "Kein erlaubtes Bodygroup auf Ihrem Modell.",
		["APPLIQUER"] = "ANWENDEN",
		["ARMURERIE"] = "WAFFENKAMMER",
		["Fondation SCP — Appuyez sur [E]"] = "SCP-Stiftung — Drücken Sie [E]",
		["Chargement déployé — %.1f kg, mobilité %d%% (%s), armure %d."]
			= "Ausrüstung eingesetzt — %.1f kg, Mobilität %d%% (%s), Panzerung %d.",
		["Certains objets ne sont pas autorisés pour votre métier et ont été retirés."]
			= "Einige Gegenstände sind für Ihren Beruf nicht erlaubt und wurden entfernt.",
		["Vous devez être à proximité d'une armoire d'armurerie pour vous équiper."]
			= "Sie müssen sich in der Nähe eines Waffenschranks befinden, um sich auszurüsten.",
		["Rendez-vous à une armoire d'armurerie pour accéder à votre équipement."]
			= "Gehen Sie zu einem Waffenschrank, um auf Ihre Ausrüstung zuzugreifen.",
		["Le panneau de configuration est réservé aux superadmins."]
			= "Das Konfigurationsmenü ist Superadmins vorbehalten.",
		["Configuration enregistrée et diffusée à tous les joueurs."]
			= "Konfiguration gespeichert und an alle Spieler gesendet.",
		["CONFIGURER VOS ARMES"] = "IHRE WAFFEN KONFIGURIEREN",
		["CONFIGURER VOTRE PROTECTION"] = "IHREN SCHUTZ KONFIGURIEREN",
		["PERSONNALISER VOTRE APPARENCE"] = "IHR AUSSEHEN ANPASSEN",
		["PARAMÈTRES ET PRÉFÉRENCES"] = "EINSTELLUNGEN UND PRÄFERENZEN",
		["APERÇU LOADOUT"] = "LOADOUT-ÜBERSICHT",
		["POIDS LOADOUT"] = "LOADOUT-GEWICHT",
		["ÉQUIPEMENT"] = "AUSRÜSTUNG",
		["QUITTER"] = "VERLASSEN",
		["REJOINDRE LE COMBAT"] = "IN DEN KAMPF",
		["ARSENAL"] = "ARSENAL",
		["UNITÉ"] = "EINHEIT",
		["SOLDAT"] = "SOLDAT",
		["GRADE"] = "RANG",
		["ÉQUIPEMENT ACTUEL"] = "AKTUELLE AUSRÜSTUNG",
		["MODIFIER"] = "ANPASSEN",
		["PROTECTION & APPARENCE"] = "SCHUTZ & AUSSEHEN",
		["REJOINDRE LA BATAILLE"] = "IN DIE SCHLACHT",
		["SAUVEGARDER LE LOADOUT"] = "LOADOUT SPEICHERN",
		["SAUVEGARDÉ"] = "GESPEICHERT",

		-- Panneau de configuration (superadmin)
		["CONFIGURATION DE L'ARMURERIE"] = "KONFIGURATION DER WAFFENKAMMER",
		["SUPERADMIN — SAUVEGARDÉE CÔTÉ SERVEUR ET DIFFUSÉE À TOUS"] = "SUPERADMIN — SERVERSEITIG GESPEICHERT UND AN ALLE VERTEILT",
		["Réservé aux superadmins."] = "Nur für Superadmins.",
		["Configuration trop volumineuse."] = "Konfiguration zu groß.",
		["ENREGISTRER ET DIFFUSER"] = "SPEICHERN UND VERTEILEN",
		["ANNULER"] = "ABBRECHEN",
		["GÉNÉRAL"] = "ALLGEMEIN",
		["INTERFACE"] = "OBERFLÄCHE",
		["JOURNAUX"] = "PROTOKOLLE",
		["AFFICHAGE & GAMEPLAY"] = "ANZEIGE & GAMEPLAY",
		["APPARENCE — BODYGROUPS MODIFIABLES PAR LES JOUEURS"] = "AUSSEHEN — VON SPIELERN ÄNDERBARE BODYGROUPS",
		["OBJETS — NOM, IMAGE IMGUR, JOBS ET GRADES MRS"] = "GEGENSTÄNDE — NAME, IMGUR-BILD, BERUFE UND MRS-RÄNGE",
		["NOM"] = "NAME",
		["Nom : renommez l'objet pour tous les joueurs (vide = nom d'origine)."] = "Name: benennen Sie den Gegenstand für alle Spieler um (leer = Originalname).",
		["N'autoriser le menu et le déploiement qu'à proximité d'une armoire d'armurerie"] = "Menü und Einsatz nur in der Nähe eines Waffenkammer-Spinds erlauben",
		["Désactiver le menu de personnalisation ARC9 (touche C) — accessoires via l'armurerie uniquement"] = "ARC9-Anpassungsmenü deaktivieren (Taste C) — Aufsätze nur über die Waffenkammer",
		["Charger automatiquement les armes des packs installés (ARC9, M9K…) — appliqué au prochain redémarrage"] = "Waffen installierter Packs automatisch laden (ARC9, M9K…) — greift beim nächsten Neustart",
		["Fond d'armurerie dans le menu : râteliers derrière l'opérateur, établi sous l'arme"] = "Waffenkammer-Hintergrund im Menü: Waffenregale hinter dem Operator, Werkbank unter der Waffe",
		["Portée autour de l'armoire (unités)"] = "Reichweite um den Spind (Einheiten)",
		["Packs d'armes non détectés : préfixes de classes chargés même sans être spawnables, séparés par des virgules."] = "Nicht erkannte Waffenpacks: Klassenpräfixe, die trotzdem geladen werden, durch Kommas getrennt.",
		["Préfixes de classes à charger (packs spéciaux)"] = "Zu ladende Klassenpräfixe (Sonderpacks)",
		["Langue de l'interface (tous les joueurs)"] = "Sprache der Oberfläche (alle Spieler)",
		["Style et couleur d'accent appliqués à tous les joueurs (pris en compte à l'ouverture de leur prochain menu)."] = "Stil und Akzentfarbe gelten für alle Spieler (wirksam beim nächsten Öffnen ihres Menüs).",
		["Choisir un style règle aussi sa couleur signature — modifiable ensuite avec les curseurs."] = "Ein Stil setzt auch seine Signaturfarbe — danach mit den Reglern änderbar.",
		["Style de l'interface"] = "Stil der Oberfläche",
		["Couleur d'accent — ROUGE"] = "Akzentfarbe — ROT",
		["Couleur d'accent — VERT"] = "Akzentfarbe — GRÜN",
		["Couleur d'accent — BLEU"] = "Akzentfarbe — BLAU",
		["Aperçu + couleurs prédéfinies"] = "Vorschau + Vorlagenfarben",
		["Fonds personnalisés : collez l'URL directe (https) de votre image — hébergez-la sur imgur par exemple."] = "Eigene Hintergründe: direkte (https) URL Ihres Bildes einfügen — z. B. auf imgur hochladen.",
		["Un fond par lieu et par style. Champ vide = fond livré avec l'addon."] = "Ein Hintergrund je Ort und Stil. Leeres Feld = mitgelieferter Hintergrund.",
		["READY OR NOT — fond de l'écran opérateur (loadout)"] = "READY OR NOT — Hintergrund des Operator-Bildschirms (Loadout)",
		["READY OR NOT — fond de l'écran modification d'arme"] = "READY OR NOT — Hintergrund des Waffenbildschirms",
		["MODERN WARFARE — fond de l'écran des cartes"] = "MODERN WARFARE — Hintergrund des Kartenbildschirms",
		["MODERN WARFARE — fond de l'écran modification d'arme"] = "MODERN WARFARE — Hintergrund des Waffenbildschirms",
		["Écrire les logs dans data/scp_armory/logs/ (un fichier par jour)"] = "Logs nach data/scp_armory/logs/ schreiben (eine Datei pro Tag)",
		["Afficher les logs dans la console serveur"] = "Logs in der Serverkonsole anzeigen",
		["Conservation des fichiers de logs (jours, 0 = illimité)"] = "Aufbewahrung der Logdateien (Tage, 0 = unbegrenzt)",
		["Distance de la caméra sur l'opérateur (plus grand = plus loin)"] = "Kameraabstand zum Operator (größer = weiter weg)",
		["Vitesse de marche de base"] = "Basis-Gehgeschwindigkeit",
		["Vitesse de course de base"] = "Basis-Laufgeschwindigkeit",
		["Armure maximale"] = "Maximale Panzerung",
		["Modèle de l'armoire"] = "Modell des Spinds",
		["Liste basée sur VOTRE playermodel actuel. Les bodygroups cochés deviennent réglables par les joueurs"] = "Liste basiert auf IHREM aktuellen Playermodel. Angehakte Bodygroups werden für Spieler einstellbar",
		["dans l'armurerie (section APPARENCE) et via !apparence. Les noms déjà autorisés sont conservés."] = "in der Waffenkammer (Bereich AUSSEHEN) und über !apparence. Bereits erlaubte Namen bleiben erhalten.",
		["Votre playermodel actuel n'a aucun bodygroup à variantes."] = "Ihr aktuelles Playermodel hat keine Bodygroups mit Varianten.",
		["Image : lien direct i.imgur.com en .png ou .jpg (vide = rendu 3D du modèle)."] = "Bild: direkter i.imgur.com-Link als .png oder .jpg (leer = 3D-Ansicht des Modells).",
		["ARMES : par défaut une arme n'est donnée à PERSONNE. Cochez ses métiers, ou TOUS LES MÉTIERS pour tout le monde."] = "WAFFEN: Standardmäßig erhält NIEMAND eine Waffe. Berufe anhaken, oder ALLE BERUFE für alle.",
		["Autres objets (tactique, grenades, gilets, casques) : aucun job coché = visible par tous, comme avant."] = "Andere Gegenstände (Taktik, Granaten, Westen, Helme): kein Beruf angehakt = für alle sichtbar, wie bisher.",
		["ARMES PRINCIPALES"] = "PRIMÄRWAFFEN",
		["ARMES SECONDAIRES"] = "SEKUNDÄRWAFFEN",
		["ÉQUIPEMENT TACTIQUE"] = "TAKTISCHE AUSRÜSTUNG",
		["GRENADES"] = "GRANATEN",
		["GILETS"] = "WESTEN",
		["CASQUES"] = "HELME",
		["IMAGE"] = "BILD",
		["JOBS"] = "BERUFE",
		["JOBS AUTORISÉS"] = "BERUFE ERLAUBT",
		["JOBS AUTORISÉS — AUCUN COCHÉ = TOUS"] = "ERLAUBTE BERUFE — KEINER ANGEHAKT = ALLE",
		["MÉTIERS — AUCUN COCHÉ = ARME DONNÉE À PERSONNE"] = "BERUFE — KEINER ANGEHAKT = WAFFE FÜR NIEMANDEN",
		["TOUS LES JOBS"] = "ALLE BERUFE",
		["TOUS LES MÉTIERS"] = "ALLE BERUFE",
		["DÉSACTIVÉ POUR TOUS"] = "FÜR ALLE DEAKTIVIERT",
		["DÉSACTIVÉ POUR TOUS (dans la liste des jobs) retire l'objet à tout le monde — même un gilet d'armure."] = "FÜR ALLE DEAKTIVIERT (in der Berufsliste) entzieht den Gegenstand jedem — sogar eine Schutzweste.",
		["Grades MRS : job ET grade se cumulent — si les deux sont réglés, il faut satisfaire les deux."] = "MRS-Ränge: Beruf UND Rang wirken zusammen — sind beide gesetzt, müssen beide erfüllt sein.",
		["Addon MRS non détecté : les restrictions par grade seront disponibles quand MRS sera installé."] = "MRS-Addon nicht gefunden: Rang-Beschränkungen werden verfügbar, sobald MRS installiert ist.",
		["AUCUN GRADE REQUIS"] = "KEIN RANG ERFORDERLICH",
		["GRADES REQUIS"] = "RÄNGE ERFORDERLICH",
		["GRADES"] = "RÄNGE",
		["GRADES MRS — AUCUN COCHÉ = PAS DE CONDITION DE GRADE"] = "MRS-RÄNGE — KEINER ANGEHAKT = KEINE RANGBEDINGUNG",
		["PERSONNE (DÉFAUT)"] = "NIEMAND (STANDARD)",
	},

	pl = {
		["ARME PRINCIPALE"] = "BROŃ GŁÓWNA",
		["ARME SECONDAIRE"] = "BROŃ BOCZNA",
		["TACTIQUE I"] = "TAKTYCZNE I",
		["TACTIQUE II"] = "TAKTYCZNE II",
		["GRENADE"] = "GRANAT",
		["GILET BALISTIQUE"] = "KAMIZELKA KULOODPORNA",
		["CASQUE"] = "HEŁM",
		["ARMEMENT"] = "UZBROJENIE",
		["PROTECTION"] = "OCHRONA",
		["APPARENCE"] = "WYGLĄD",
		["PRÉPARATION AU DÉPLOIEMENT"] = "PRZYGOTOWANIE DO AKCJI",
		["MODIFIER L'ARME"] = "MODYFIKUJ BROŃ",
		["CHOIX D'ACCESSOIRE"] = "WYBÓR DODATKU",
		["SÉLECTION D'ÉQUIPEMENT"] = "WYBÓR WYPOSAŻENIA",
		["APPARENCE DE L'OPÉRATEUR"] = "WYGLĄD OPERATORA",
		["— AUCUN —"] = "— BRAK —",
		["— AUCUNE —"] = "— BRAK —",
		["CHANGER D'ARME"] = "ZMIEŃ BROŃ",
		["—  VIDE  —"] = "—  PUSTE  —",
		["RETIRER TOUS LES ACCESSOIRES"] = "USUŃ WSZYSTKIE DODATKI",
		["SÉLECTIONNEZ D'ABORD UNE ARME"] = "NAJPIERW WYBIERZ BROŃ",
		["ARME NON ARC9 — AUCUN ACCESSOIRE DISPONIBLE"] = "BROŃ SPOZA ARC9 — BRAK DOSTĘPNYCH DODATKÓW",
		["CETTE ARME N'A AUCUN EMPLACEMENT D'ACCESSOIRE"] = "TA BROŃ NIE MA GNIAZD NA DODATKI",
		["AUCUN EMPLACEMENT D'ACCESSOIRE"] = "BRAK GNIAZD NA DODATKI",
		["—  AUCUN  —"] = "—  BRAK  —",
		["CONFIGURATION"] = "KONFIGURACJA",
		["AUCUN ACCESSOIRE ARC9 COMPATIBLE INSTALLÉ"] = "BRAK ZGODNEGO DODATKU ARC9",
		["ACCESSOIRES"] = "DODATKI",
		["AUCUNE ARME SÉLECTIONNÉE"] = "NIE WYBRANO BRONI",
		["ARME NON ARC9 — PAS DE RAIL"] = "BROŃ SPOZA ARC9 — BRAK SZYNY",
		["PRINCIPALE"] = "GŁÓWNA",
		["SECONDAIRE"] = "BOCZNA",
		["‹  RETOUR"] = "‹  POWRÓT",
		["RETOUR"] = "POWRÓT",
		["DÉPLOYER"] = "DO AKCJI",
		["CHARGEMENT"] = "OBCIĄŻENIE",
		["POIDS"] = "WAGA",
		["MOBILITÉ"] = "MOBILNOŚĆ",
		["ARMURE"] = "PANCERZ",
		["LÉGER"] = "LEKKIE",
		["INTERMÉDIAIRE"] = "ŚREDNIE",
		["LOURD"] = "CIĘŻKIE",
		["DÉGÂTS"] = "OBRAŻENIA",
		["CADENCE"] = "SZYBKOSTRZELNOŚĆ",
		["CONTRÔLE"] = "KONTROLA",
		["PRÉCISION"] = "CELNOŚĆ",
		["VARIANTE"] = "WARIANT",
		["ÉQUIPÉE"] = "ZAŁOŻONY",
		["GLISSER : PIVOTER   ·   MOLETTE : ZOOM   ·   CLIC MOLETTE : DÉPLACER"]
			= "PRZECIĄGNIJ: OBRÓT   ·   KÓŁKO: ZOOM   ·   ŚRODKOWY PRZYCISK: PRZESUŃ",
		["BODYGROUPS AUTORISÉS PAR LE SITE"] = "BODYGROUPS DOZWOLONE PRZEZ PLACÓWKĘ",
		["Aucun bodygroup autorisé sur votre modèle."] = "Brak dozwolonych bodygroups na Twoim modelu.",
		["APPLIQUER"] = "ZASTOSUJ",
		["ARMURERIE"] = "ZBROJOWNIA",
		["Fondation SCP — Appuyez sur [E]"] = "Fundacja SCP — Naciśnij [E]",
		["Chargement déployé — %.1f kg, mobilité %d%% (%s), armure %d."]
			= "Wyposażenie wydane — %.1f kg, mobilność %d%% (%s), pancerz %d.",
		["Certains objets ne sont pas autorisés pour votre métier et ont été retirés."]
			= "Niektóre przedmioty nie są dozwolone dla Twojej profesji i zostały usunięte.",
		["Vous devez être à proximité d'une armoire d'armurerie pour vous équiper."]
			= "Musisz być w pobliżu szafy zbrojowni, aby się wyposażyć.",
		["Rendez-vous à une armoire d'armurerie pour accéder à votre équipement."]
			= "Udaj się do szafy zbrojowni, aby uzyskać dostęp do wyposażenia.",
		["Le panneau de configuration est réservé aux superadmins."]
			= "Panel konfiguracji jest zarezerwowany dla superadminów.",
		["Configuration enregistrée et diffusée à tous les joueurs."]
			= "Konfiguracja zapisana i rozesłana do wszystkich graczy.",
		["CONFIGURER VOS ARMES"] = "SKONFIGURUJ SWOJĄ BROŃ",
		["CONFIGURER VOTRE PROTECTION"] = "SKONFIGURUJ SWOJĄ OCHRONĘ",
		["PERSONNALISER VOTRE APPARENCE"] = "DOSTOSUJ SWÓJ WYGLĄD",
		["PARAMÈTRES ET PRÉFÉRENCES"] = "USTAWIENIA I PREFERENCJE",
		["APERÇU LOADOUT"] = "PODGLĄD WYPOSAŻENIA",
		["POIDS LOADOUT"] = "WAGA WYPOSAŻENIA",
		["ÉQUIPEMENT"] = "WYPOSAŻENIE",
		["QUITTER"] = "WYJDŹ",
		["REJOINDRE LE COMBAT"] = "DO WALKI",
		["ARSENAL"] = "ARSENAŁ",
		["UNITÉ"] = "JEDNOSTKA",
		["SOLDAT"] = "ŻOŁNIERZ",
		["GRADE"] = "STOPIEŃ",
		["ÉQUIPEMENT ACTUEL"] = "OBECNE WYPOSAŻENIE",
		["MODIFIER"] = "MODYFIKUJ",
		["PROTECTION & APPARENCE"] = "OCHRONA I WYGLĄD",
		["REJOINDRE LA BATAILLE"] = "DO BITWY",
		["SAUVEGARDER LE LOADOUT"] = "ZAPISZ WYPOSAŻENIE",
		["SAUVEGARDÉ"] = "ZAPISANO",

		-- Panneau de configuration (superadmin)
		["CONFIGURATION DE L'ARMURERIE"] = "KONFIGURACJA ZBROJOWNI",
		["SUPERADMIN — SAUVEGARDÉE CÔTÉ SERVEUR ET DIFFUSÉE À TOUS"] = "SUPERADMIN — ZAPISYWANA NA SERWERZE I ROZSYŁANA DO WSZYSTKICH",
		["Réservé aux superadmins."] = "Tylko dla superadminów.",
		["Configuration trop volumineuse."] = "Konfiguracja zbyt duża.",
		["ENREGISTRER ET DIFFUSER"] = "ZAPISZ I ROZEŚLIJ",
		["ANNULER"] = "ANULUJ",
		["GÉNÉRAL"] = "OGÓLNE",
		["INTERFACE"] = "INTERFEJS",
		["JOURNAUX"] = "LOGI",
		["AFFICHAGE & GAMEPLAY"] = "WYŚWIETLANIE I ROZGRYWKA",
		["APPARENCE — BODYGROUPS MODIFIABLES PAR LES JOUEURS"] = "WYGLĄD — BODYGROUPY DOSTĘPNE DLA GRACZY",
		["OBJETS — NOM, IMAGE IMGUR, JOBS ET GRADES MRS"] = "PRZEDMIOTY — NAZWA, OBRAZ IMGUR, ZAWODY I STOPNIE MRS",
		["NOM"] = "NAZWA",
		["Nom : renommez l'objet pour tous les joueurs (vide = nom d'origine)."] = "Nazwa: zmień nazwę przedmiotu dla wszystkich graczy (puste = nazwa oryginalna).",
		["N'autoriser le menu et le déploiement qu'à proximité d'une armoire d'armurerie"] = "Zezwalaj na menu i wyposażenie tylko przy szafie zbrojowni",
		["Désactiver le menu de personnalisation ARC9 (touche C) — accessoires via l'armurerie uniquement"] = "Wyłącz menu modyfikacji ARC9 (klawisz C) — dodatki tylko przez zbrojownię",
		["Charger automatiquement les armes des packs installés (ARC9, M9K…) — appliqué au prochain redémarrage"] = "Automatycznie wczytuj bronie zainstalowanych paczek (ARC9, M9K…) — od następnego restartu",
		["Fond d'armurerie dans le menu : râteliers derrière l'opérateur, établi sous l'arme"] = "Tło zbrojowni w menu: stojaki za operatorem, warsztat pod bronią",
		["Portée autour de l'armoire (unités)"] = "Zasięg wokół szafy (jednostki)",
		["Packs d'armes non détectés : préfixes de classes chargés même sans être spawnables, séparés par des virgules."] = "Niewykryte paczki broni: prefiksy klas wczytywane mimo wszystko, rozdzielone przecinkami.",
		["Préfixes de classes à charger (packs spéciaux)"] = "Prefiksy klas do wczytania (paczki specjalne)",
		["Langue de l'interface (tous les joueurs)"] = "Język interfejsu (wszyscy gracze)",
		["Style et couleur d'accent appliqués à tous les joueurs (pris en compte à l'ouverture de leur prochain menu)."] = "Styl i kolor akcentu obowiązują wszystkich graczy (od następnego otwarcia ich menu).",
		["Choisir un style règle aussi sa couleur signature — modifiable ensuite avec les curseurs."] = "Wybór stylu ustawia też jego kolor — potem można go zmienić suwakami.",
		["Style de l'interface"] = "Styl interfejsu",
		["Couleur d'accent — ROUGE"] = "Kolor akcentu — CZERWONY",
		["Couleur d'accent — VERT"] = "Kolor akcentu — ZIELONY",
		["Couleur d'accent — BLEU"] = "Kolor akcentu — NIEBIESKI",
		["Aperçu + couleurs prédéfinies"] = "Podgląd + gotowe kolory",
		["Fonds personnalisés : collez l'URL directe (https) de votre image — hébergez-la sur imgur par exemple."] = "Własne tła: wklej bezpośredni adres (https) swojego obrazka — np. z imgur.",
		["Un fond par lieu et par style. Champ vide = fond livré avec l'addon."] = "Jedno tło na miejsce i styl. Puste pole = tło dołączone do dodatku.",
		["READY OR NOT — fond de l'écran opérateur (loadout)"] = "READY OR NOT — tło ekranu operatora (loadout)",
		["READY OR NOT — fond de l'écran modification d'arme"] = "READY OR NOT — tło ekranu modyfikacji broni",
		["MODERN WARFARE — fond de l'écran des cartes"] = "MODERN WARFARE — tło ekranu kart",
		["MODERN WARFARE — fond de l'écran modification d'arme"] = "MODERN WARFARE — tło ekranu modyfikacji broni",
		["Écrire les logs dans data/scp_armory/logs/ (un fichier par jour)"] = "Zapisuj logi do data/scp_armory/logs/ (jeden plik dziennie)",
		["Afficher les logs dans la console serveur"] = "Pokazuj logi w konsoli serwera",
		["Conservation des fichiers de logs (jours, 0 = illimité)"] = "Przechowywanie plików logów (dni, 0 = bez limitu)",
		["Distance de la caméra sur l'opérateur (plus grand = plus loin)"] = "Odległość kamery od operatora (większa = dalej)",
		["Vitesse de marche de base"] = "Bazowa prędkość chodu",
		["Vitesse de course de base"] = "Bazowa prędkość biegu",
		["Armure maximale"] = "Maksymalny pancerz",
		["Modèle de l'armoire"] = "Model szafy",
		["Liste basée sur VOTRE playermodel actuel. Les bodygroups cochés deviennent réglables par les joueurs"] = "Lista oparta na TWOIM obecnym modelu gracza. Zaznaczone bodygroupy stają się dostępne dla graczy",
		["dans l'armurerie (section APPARENCE) et via !apparence. Les noms déjà autorisés sont conservés."] = "w zbrojowni (sekcja WYGLĄD) i przez !apparence. Już dozwolone nazwy zostają zachowane.",
		["Votre playermodel actuel n'a aucun bodygroup à variantes."] = "Twój obecny model gracza nie ma bodygroupów z wariantami.",
		["Image : lien direct i.imgur.com en .png ou .jpg (vide = rendu 3D du modèle)."] = "Obraz: bezpośredni link i.imgur.com jako .png lub .jpg (puste = widok 3D modelu).",
		["ARMES : par défaut une arme n'est donnée à PERSONNE. Cochez ses métiers, ou TOUS LES MÉTIERS pour tout le monde."] = "BRONIE: domyślnie broń nie jest przydzielona NIKOMU. Zaznacz jej zawody albo WSZYSTKIE ZAWODY dla wszystkich.",
		["Autres objets (tactique, grenades, gilets, casques) : aucun job coché = visible par tous, comme avant."] = "Pozostałe przedmioty (taktyczne, granaty, kamizelki, hełmy): brak zaznaczonego zawodu = widoczne dla wszystkich, jak dotąd.",
		["ARMES PRINCIPALES"] = "BRONIE GŁÓWNE",
		["ARMES SECONDAIRES"] = "BRONIE BOCZNE",
		["ÉQUIPEMENT TACTIQUE"] = "SPRZĘT TAKTYCZNY",
		["GRENADES"] = "GRANATY",
		["GILETS"] = "KAMIZELKI",
		["CASQUES"] = "HEŁMY",
		["IMAGE"] = "OBRAZ",
		["JOBS"] = "ZAWODY",
		["JOBS AUTORISÉS"] = "DOZWOLONE ZAWODY",
		["JOBS AUTORISÉS — AUCUN COCHÉ = TOUS"] = "DOZWOLONE ZAWODY — BRAK ZAZNACZEŃ = WSZYSCY",
		["MÉTIERS — AUCUN COCHÉ = ARME DONNÉE À PERSONNE"] = "ZAWODY — BRAK ZAZNACZEŃ = BROŃ DLA NIKOGO",
		["TOUS LES JOBS"] = "WSZYSTKIE ZAWODY",
		["TOUS LES MÉTIERS"] = "WSZYSTKIE ZAWODY",
		["DÉSACTIVÉ POUR TOUS"] = "WYŁĄCZONE DLA WSZYSTKICH",
		["DÉSACTIVÉ POUR TOUS (dans la liste des jobs) retire l'objet à tout le monde — même un gilet d'armure."] = "WYŁĄCZONE DLA WSZYSTKICH (na liście zawodów) zabiera przedmiot każdemu — nawet kamizelkę.",
		["Grades MRS : job ET grade se cumulent — si les deux sont réglés, il faut satisfaire les deux."] = "Stopnie MRS: zawód I stopień łączą się — gdy oba są ustawione, trzeba spełnić oba.",
		["Addon MRS non détecté : les restrictions par grade seront disponibles quand MRS sera installé."] = "Nie wykryto dodatku MRS: ograniczenia stopni będą dostępne po jego zainstalowaniu.",
		["AUCUN GRADE REQUIS"] = "BEZ WYMAGANEGO STOPNIA",
		["GRADES REQUIS"] = "WYMAGANE STOPNIE",
		["GRADES"] = "STOPNIE",
		["GRADES MRS — AUCUN COCHÉ = PAS DE CONDITION DE GRADE"] = "STOPNIE MRS — BRAK ZAZNACZEŃ = BEZ WARUNKU STOPNIA",
		["PERSONNE (DÉFAUT)"] = "NIKT (DOMYŚLNIE)",
	},
}

-- Traduction d'une chaîne française vers la langue configurée
function SCPArmory.T(s)
	local lang = SCPArmory.Config and SCPArmory.Config.Language or "fr"
	if lang == "fr" then return s end
	local t = SCPArmory.Translations[lang]
	return (t and t[s]) or s
end
